version: '3'
services:
  iot:
    image: frametest
    ports:
      - "2540:2540"
    environment:
      CLUSTER_IP: iot
      CLUSTER_PORT: 2540
      SEED1_IP: iot
      SEED1_PORT: 2540
      MASTER_SYSTEM_NAME: MasterSystem
      MASTER_IP: master
      MASTER_PORT: 2550
      MQTT_IP: mqttbroker
      MQTT_PORT: 1883
      CASSANDRA_SEED: cass
      #      SEED2_TCP_ADDR: seed2
      ROLE: iot
    networks:
      - akka-wsn
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    command: gradle run --args="iot 1"
#
  worker1:
    image: frametest
    ports:
      - "2560:2560" # Akka port
      - "8558:8558" # Http Management port
    environment:
      CLUSTER_IP: worker1
      CLUSTER_PORT: 2560
      SEED1_IP: worker1
      SEED1_PORT: 2560
      MASTER_SYSTEM_NAME: MasterSystem
      MASTER_IP: master
      MASTER_PORT: 2550
      #      SEED2_TCP_ADDR: seed2
      CASSANDRA_SEED: cass
      ROLE: worker
    networks:
      - akka-wsn
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
        delay: 10s
    command: gradle run --args="worker"

  mqttbroker:
#    image: arm32v6/eclipse-mosquitto
    image: eclipse-mosquitto
    ports:
      - "1883:1883" # Listen port
      - "9001:9001" # Websocket port
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - akka-wsn

  cass:
    image: cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: CassandraCluster
    networks:
      - akka-wsn
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
        delay: 10s

  master:
    image: frametest
    ports:
      - "2550:2550"
    environment:
      CLUSTER_IP: master
      CLUSTER_PORT: 2550
      SEED1_IP: master
      SEED1_PORT: 2550
      MASTER_SYSTEM_NAME: MasterSystem
      CASSANDRA_SEED: cass
      #      SEED2_TCP_ADDR: seed2
      ROLE: master
    networks:
      - akka-wsn
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
        delay: 20s
      update_config:
        parallelism: 1
        delay: 10s
    command: gradle run --args="master"

networks:
  akka-wsn: